ecomm/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('ecomm_app.urls')),
    
]

ecomm_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Product(models.Model):
    CAT=((1,'Mobile'),(2,'Shoe'),(3,'Clothes'))
    name=models.CharField(max_length=50,verbose_name='Product Name')
    price=models.FloatField()
    pdetails=models.CharField(max_length=2000,verbose_name='Product Detail')
    cat=models.IntegerField(verbose_name="Category",choices=CAT)
    is_active=models.BooleanField(default=True,verbose_name='Available')
    pimage=models.ImageField(upload_to='image')
    # def __str__(self):
    #     return self.name

class Cart(models.Model):
    uid=models.ForeignKey(User,on_delete=models.CASCADE,db_column="uid")
    pid=models.ForeignKey(Product,on_delete=models.CASCADE,db_column="pid")
    qty=models.IntegerField(default=1)

class Order(models.Model):
    order_id=models.CharField(max_length=50)
    uid=models.ForeignKey(User,on_delete=models.CASCADE,db_column="uid")
    pid=models.ForeignKey(Product,on_delete=models.CASCADE,db_column="pid")
    qty=models.IntegerField(default=1)

templates/base.html
{% include 'header.html' %}

{% block 'main' %}


{% endblock 'main' %}

{% include 'footer.html' %}

templates/cart.html
{% extends 'base.html' %}
{% load static %}

{% block 'main' %}

<!--Cart start-->
<div class="row mt-3">
    <div class="col-md-9">
        <h5 class="bg-danger text-white p-2">Customer Details</h5>
        <p><strong>Name: </strong>{{user.username}}</p>
        <p><strong>Mobile: </strong>9090909090</p>
        <p><strong>Email: </strong>{{user.email}}</p>
        <h5 class="bg-danger text-white p-2">Product Details</h5>
        {% for x in data %}
        <div class="row mt-2">
            <div class="col-md-6">
                <img src="{{x.pid.pimage.url}}" width="100%" card-img-top alt="...">
            </div>
            <div class="col-md-6">
                <p><strong>Product Name:</strong> {{x.pid.name}}</p>
                <p><strong>Price:</strong>{{x.pid.price}}</p>
                <p><strong>Category:</strong>{{x.pid.get_cat_display}}</p>
                <p><strong>Product Description:</strong>{{x.pid.pdetails}}</p>
                <p>
                    <strong>QTY:</strong>
                    <a herf="/updateqty/0/{{x.id}}" class="btn btn-danger">-</a>
                    <input type="number" value="{{x.qty}}" >
                    <a herf="/updateqty/1/{{x.id}}" class="btn btn-success">+</a>
                </p>
                <a href="/remove/{{x.id}}" class="btn btn-danger">Remove</a>
            </div>
        </div>
        {% endfor %}

    </div><!--customer and product detail-->
    <div class="col-md-3">
        <h5 class="bg-danger text-white p-2">Total amount</h5>
        <p><strong>Total({{n}}Item):</strong> Rs{{total}}</p>
        <hr>
        <p><strong>Total Amount:</strong> Rs{{total}}</p>
        <a href="/placeorder" class="btn btn-danger">Place order</a>

    </div><!-- total amount section-->
</div>





<!--Cart end-->

{% endblock 'main' %}

templates/footer.html
{% load static %}
        <!---footer start-->
        <div class="row">
            <div class="col-md-4">
              <h5>Address</h5> <hr>
              F-501 Yogiraj Ashish Apartment<br>
              Near 8-rasta chowk<br>
              Laxmi,Nagar-Nagpur<br><br>
              <p>
                <i class="bi bi-telephone-fill text-danger"></i> Contact Number:9090909090
              </p>
              <p>
                <i class="bi bi-envelope-fill text-danger"></i> anonymous@gmail.com
              </p>
            </div>
            <div class="col-md-4">
              <h5>Quick Links</h5> <hr>
              <p><a href="index.html" class="anchor">Home</a></p>
              <p><a href="about.html" class="anchor">About</a></p>
              <p><a href="cart.html" class="anchor">Cart</a></p>
              <p><a href="contact.html" class="anchor">Contact</a></p>
            </div>
            <div class="col-md-4">
              <h5>Contact Us</h5> <hr>
              <h5><a href="http://www.facebook.com"><i class="bi bi-facebook text-danger"></i></a></h5>
              <h5><a href="http://www.instagram.com"><i class="bi bi-instagram text-danger"></i></a></h5>
              <h5><a href="http://www.twitter.com"><i class="bi bi-twitter text-danger"></i></a></h5>
              <h5><a href="http://www.linkedin.com"><i class="bi bi-linkedin text-danger"></i></a></h5>
  
            </div>
          </div>
  
          <!---footer start-->
      </div><!--- container end --->
      
  
      <script src="{% static 'assets/js/bootstrap.min.js' %}" ></script>
  </body>
  </html>

templates/header.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home page</title>
    <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
  </head>
<body>
    <!--<h1>home</h1>-->
    <div class="container">
        <div class="row mt-5">
            <div class="col-md-12">
                <nav class="navbar navbar-expand-lg navbar-light bg-light">
                    <div class="container-fluid">
                      <a class="navbar-brand" href="#">E-Store</a>
                      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                      </button>
                      <div class="collapse navbar-collapse" id="navbarNav">
                        <ul class="navbar-nav">
                          <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="/index">Home</a>
                          </li>
                          <li class="nav-item">
                            <a class="nav-link" href="/about">About</a>
                            <li class="nav-item">
                              <a class="nav-link" href="/contact">Contact</a>
                          </li>
                          <li class="nav-item">
                            <a class="nav-link" href="/viewcart">Cart</a>
                          </li>
                          {% if user.is_authenticated %}
                          <li class="nav-item">
                            <a class="nav-link" href="/logout">Logout</a>
                          </li>
                          {% else %}
                          <li class="nav-item">
                            <a class="nav-link" href="/login">Login</a>
                          </li>
                          <li class="nav-item">
                            <a class="nav-link" href="/register">Register</a>
                          </li>
                          {% endif %}
                        </ul>
                      </div>
                    </div>
                  </nav>

            </div><!---Navigation bar col ends--->
        </div><!---Navigation row end--->
        <!-- header ends -->

templates/hello.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Templates</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <h1>Templates as Response</h1>
    <p>Data is:{{greet}}</p>
    {% comment %}
    {{x}}<br>
    {{y}}
    {% if x > y %}
        <p>{{x} is greater}</p>
    {% else %}
        <p>{{y} is greater}</p>
    {% endif %}

    {% for x in l %}
         {{x}}<br>
    {% endfor %}

        
    {% for x in products %}
        <!-- <p>{{x}}</p> -->
        <strong>Sr. No:</strong> {{forloop.counter}}<br>
        <strong>Name:</strong> {{x.name}}<br>
        <strong>Category:</strong> {{x.cat}}<br>
        <strong>Price:</strong> {{x.price}}<br>
        <hr>
    {% endfor %}
    {% endcomment %}
    <button onclick="greet()">click me</button><br>

    <img src="{% static 'images/bmw.jpg' %}" alt="" width="200px" height="200px">
    <script src="{% static 'js/main.js' %}"></script>

</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block 'main' %}

        <!--Main content starts-->
        <div class="row mt-3">
            <div class="col-md-4 bg-light">
              <h5>Filter by category</h5>
              <hr>
              <p><a href="/catfilter/1" class="anchor">By mobile </a></p>
              <p><a href="/catfilter/2" class="anchor">By Shoes</a></p>
              <p><a href="/catfilter/3" class="anchor">By clothes</a></p>
              <h5>Filter by Price Range</h5>
              <hr>
              <form action="/range">
                <div calss="mb-3">
                  <label for="input1" class="from-label">Min Value:</label>
                  <input type="number" name="min" class="form-control" id="input1" placeholder="minimumvalue">
                </div>
                <div calss="mb-3">
                  <label for="input2" class="from-label">Max Value:</label>
                  <input type="number" name="max" class="form-control" id="input2" placeholder="maximumvalue">
                </div>
                <div calss="mb-3">
                  <input type="submit" class="btn btn-secondary" value="submit">
                </div>
              </form>
              <h5>Sort by Price</h5>
              <hr>
              <p><a href="/sort/0" class="anchor">Low to High</a></p>
              <p><a href="/sort/1" class="anchor">High to Low</a></p>
  
            </div> <!-- filter sidebar ends -->
            <div class="col md-8">
              <div class="row">
                {% for x in products %}
                <div class="col-md-4 mt-2">
                  <div class="card" style="width: 100%;">
                    <img src="{{x.pimage.url}}" class="card-img-top" height="200px" alt="...">
                    <div class="card-body">
                      <h5 class="card-title">{{x.name}}</h5>
                      <p class="card-text">Rs.{{x.price}}</p>
                      {% if x.cat == 1 %}
                      <p class="card-text">Mobile</p>
                      {% elif x.cat == 2 %}
                      <p class="card-text">Shoes</p>
                      {% else %}
                      <p class="card-text">Clothes</p>
                      {% endif %}
                      <a href="/pdetails/{{x.id}}" class="btn btn-danger">See Details</a>
                    </div>
                  </div>
                </div><!--Product 1-->
                {% endfor %}
              </div>
            </div><!--product ends-->
          </div><!--filter and product sec end -->

{% endblock 'main' %}

templates/login.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}" />
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-md-4 shadow mt-4 p-4 mx-auto">
                <h2 align="center">Login</h2>
                {% if errmsg %}
                <div class="alert alert-danger">
                    {{errmsg}}
                </div>
                {% endif %}
                <form method="POST" action="/login">
                    {% csrf_token %}
                    <div>
                        <div class="mb-3">
                            <label for="input1" class="form-label"><strong>Email address</strong></label>
                            <input type="email" name="uname" class="form-control" id="input1" placeholder="Enter Email">
                        </div> <!--email end-->
                        <div class="mb-3">
                            <label for="input3" class="form-label"><strong>Password:</strong></label>
                            <input type="password" name="upass" class="form-control" id="input3" placeholder="Enter Password ">
                        </div><!-- password end-->
                        <div class="mb-3">
                            <input type="submit" class="btn btn-secondary" value="Login" />
                            Not User? <a href="/register">Register</a>
                        </div><!--Submit button--->
                        {% if success %}
                        <div class="alert alert-danger">
                            {{success}}
                        </div>
                        {% endif %}
                    </div>
                </form>
            </div>
        </div>

    </div>
    <script src="{% static 'assets/js/bootstrap.min.js' %}" ></script>
</body>
</html>

templates/pay.html
{% extends 'base.html' %}

{% block 'main' %}
<br>
<button id="rzp-button1" class="btn btn-danger m-5">Pay with Razorpay</button>
<script src="https://checkout.razorpay.com/v1/checkout.js"></script>
<script>
var options = {
    "key": "rzp_test_pjmfONoAV5hhRJ", // Enter the Key ID generated from the Dashboard
    "amount": "{{data.amount}}", // Amount is in currency subunits. Default currency is INR. Hence, 50000 refers to 50000 paise
    "currency": "INR",
    "name": "Estore pvt ltd.",
    "description": "Test Transaction",
    "image": "https://example.com/your_logo",
    "order_id": "{{data.id}}", //This is a sample Order ID. Pass the `id` obtained in the response of Step 1
    "handler": function (response){
        //alert(response.razorpay_payment_id);
        //alert(response.razorpay_order_id);
        //alert(response.razorpay_signature)
        window.location.href="http://localhost:8000/sendmail/{{uemail}}"
    },
    "prefill": {
        "name": "Gaurav Kumar",
        "email": "gaurav.kumar@example.com",
        "contact": "9000090000"
    },
    "notes": {
        "address": "Razorpay Corporate Office"
    },
    "theme": {
        "color": "#3399cc"
    }
};
var rzp1 = new Razorpay(options);
rzp1.on('payment.failed', function (response){
        alert(response.error.code);
        alert(response.error.description);
        alert(response.error.source);
        alert(response.error.step);
        alert(response.error.reason);
        alert(response.error.metadata.order_id);
        alert(response.error.metadata.payment_id);
});
document.getElementById('rzp-button1').onclick = function(e){
    rzp1.open();
    e.preventDefault();
}
</script>

{% endblock 'main' %}

templates/placeorder.html
{% extends 'base.html' %}
{% load static %}

{% block 'main' %}

<!--Cart start-->
<div class="row mt-3">
    <div class="col-md-9">
        <h5 class="bg-danger text-white p-2">Customer Details</h5>
        <p><strong>Name: </strong>{{user.username}}</p>
        <p><strong>Mobile: </strong>9090909090</p>
        <p><strong>Email: </strong>{{user.email}}</p>
        <h5 class="bg-danger text-white p-2">Product Details</h5>
        {% for x in data %}
        <div class="row mt-2">
            <div class="col-md-6">
                <img src="{{x.pid.pimage.url}}" width="100%" card-img-top alt="...">
            </div>
            <div class="col-md-6">
                <p><strong>Product Name:</strong> {{x.pid.name}}</p>
                <p><strong>Price:</strong>{{x.pid.price}}</p>
                <p><strong>Category:</strong>{{x.pid.get_cat_display}}</p>
                <p><strong>Product Description:</strong>{{x.pid.pdetails}}</p>
                <!-- <p>
                    <strong>QTY:</strong>
                    <a herf="/updateqty/0/{{x.id}}" class="btn btn-danger">-</a>
                    <input type="number" value="{{x.qty}}" readonly>
                    <a herf="/updateqty/1/{{x.id}}" class="btn btn-success">+</a>
                </p> -->
                <a href="/remove/{{x.id}}" class="btn btn-danger">Remove</a>
            </div>
        </div>
        {% endfor %}

    </div><!--customer and product detail-->
    <div class="col-md-3">
        <h5 class="bg-danger text-white p-2">Total amount</h5>
        <p><strong>Total({{n}}Item):</strong> Rs{{total}}</p>
        <hr>
        <p><strong>Total Amount:</strong> Rs{{total}}</p>
        <a href="/makepayment" class="btn btn-danger">Make Payment</a>

    </div><!-- total amount section-->
</div>





<!--Cart end-->

{% endblock 'main' %}

templates/product_details.html
{% extends 'base.html' %}
{% load static %}

{% block 'main' %}
   
        <!--Main start-->
        <div class="row mt-3">
            {% for x in products %}
            <div class="col-md-6">
                <img src="{{x.pimage.url}}" width="100%" class="card-img-top" alt=...>
            </div>
            <div class="col-md-6">
                <p><strong>Product Name</strong>Iphone 15 Pro</p>
                <p><strong>Price:</strong> {{x.price}}</p>
                {% if x.cat == 1 %}
                <p><strong>Category</strong>Mobile</p>
                {% elif x.cat == 2 %}
                <p><strong>Category</strong>Shoes</p>
                {% else %}
                <p><strong>Category</strong>Clothes</p>
                {% endif %}
                <p><strong>Product Description</strong>{{x.pdetails}}</p>
                <br>
                <a href="/addtocart/{{x.id}}" class="btn btn-danger">Add To Cart</a>&nbsp;&nbsp;&nbsp;
                <a href="/viewcart" class="btn btn-danger">View Cart</a>&nbsp;&nbsp;&nbsp;
                <a href="/" class="btn btn-danger">Shop More</a>
                {% if success %}
                <div class="alert alert-success">
                    {{success}}
                </div>
                {% endif %}
                {% if errmsg %}
                <div class="alert alert-danger">
                    {{errmsg}}
                </div>
                {% endif %}
            </div>
            {% endfor %}
        </div>





        <!--Main end-->

{% endblock 'main' %}

templates/register.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Register</title>
    <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}" />
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-md-4 shadow mt-4 p-4 mx-auto">
                <h2 align="center">Registration</h2>
                {% if errmsg %}
                <div class="alert alert-danger">
                    {{errmsg}}
                </div>
                {% endif %}
                <form method="POST" action="/register">
                    {% csrf_token %}
                    <div>
                        <div class="mb-3">
                            <label for="input1" class="form-label"><strong>Email address</strong></label>
                            <input type="email" name="uname" class="form-control" id="input1" placeholder="Enter Email">
                        </div> <!--email end-->
                        <div class="mb-3">
                            <label for="input2" class="form-label"><strong>Password:</strong></label>
                            <input type="password" name="upass"  class="form-control" id="input2" placeholder="Enter Password">
                        </div><!-- password end-->
                        <div class="mb-3">
                            <label for="input3" class="form-label"><strong>Confirm Password:</strong></label>
                            <input type="password" name="ucpass" class="form-control" id="input3" placeholder="Enter Password again">
                        </div><!--confirm password end-->
                        <div class="mb-3">
                            <input type="submit" class="btn btn-secondary" value="Register" />
                            Already User? <a href="/login">Login</a>
                        </div><!--Submit button--->
                        {% if success %}
                        <div class="alert alert-danger">
                            {{success}}
                        </div>
                        {% endif %}
                    </div>
                </form>
            </div>
        </div>

    </div>
    <script src="{% static 'assets/js/bootstrap.min.js' %}" ></script>
</body>
</html>